TRAIN_DATA_EN = [
    ("Alice walked through the dark garden.", { "entities": [(0, 5, "CHARACTER"), (31, 37, "LOCATION")] }),
    ("The old wizard cast a spell in the tower.", { "entities": [(8, 14, "CHARACTER"), (35, 41, "LOCATION")] }),
    ("Maria whispered a secret to John near the fountain.", { "entities": [(0, 5, "CHARACTER"), (30, 34, "CHARACTER"), (44, 52, "ENVIRONMENT_ELEMENT")] }),
    ("Captain Blackbeard sailed the seas with his crew.", { "entities": [(0, 18, "CHARACTER"), (30, 34, "LOCATION"), (44, 48, "GROUP")] }),
    ("The young princess smiled in the castle hall.", { "entities": [(4, 19, "CHARACTER"), (34, 45, "LOCATION")] }),
    ("Detective Holmes solved the case in his study.", { "entities": [(0, 17, "CHARACTER"), (43, 48, "LOCATION")] }),
    ("A mysterious stranger appeared at the crossroads.", { "entities": [(2, 22, "CHARACTER"), (40, 50, "LOCATION")] }),
    ("Queen Elizabeth ruled wisely from the throne room.", { "entities": [(0, 17, "CHARACTER"), (39, 50, "LOCATION")] }),
    ("The brave knight drew his sword before the battle.", { "entities": [(4, 17, "CHARACTER"), (27, 32, "ITEM")] }),
    ("Little Red Riding Hood met the wolf in the forest.", { "entities": [(0, 24, "CHARACTER"), (33, 37, "CHARACTER"), (45, 51, "LOCATION")] }),

    ("The royal guards surrounded the castle at dawn.", { "entities": [(4, 16, "GROUP"), (31, 37, "LOCATION")] }),
    ("A band of thieves stole the treasure from the vault.", { "entities": [(2, 18, "GROUP"), (30, 38, "ITEM"), (49, 54, "LOCATION")] }),
    ("Villagers gathered in the square during the Harvest Festival.", { "entities": [(0, 9, "GROUP"), (22, 28, "LOCATION"), (41, 58, "EVENT")] }),
    ("The army marched at dawn toward the enemy fortress.", { "entities": [(4, 8, "GROUP"), (37, 52, "LOCATION")] }),
    ("A crew of pirates searched the island for the ancient map.", { "entities": [(2, 18, "GROUP"), (30, 36, "LOCATION"), (55, 66, "ITEM")] }),

    ("Alice entered the dark forest near the crystal stream.", { "entities": [(0, 5, "CHARACTER"), (23, 29, "LOCATION"), (44, 58, "ENVIRONMENT_ELEMENT")] }),
    ("They sailed across the Atlantic Ocean toward the mysterious island.", { "entities": [(21, 37, "LOCATION"), (56, 73, "LOCATION")] }),
    ("The castle stood on the hill overlooking the valley.", { "entities": [(4, 10, "LOCATION"), (23, 27, "ENVIRONMENT_ELEMENT"), (44, 50, "LOCATION")] }),
    ("Maria lived in Paris, in a small apartment near the Seine.", { "entities": [(0, 5, "CHARACTER"), (16, 21, "LOCATION"), (55, 60, "LOCATION")] }),
    ("The journey to Mount Everest was dangerous due to the blizzard.", { "entities": [(15, 28, "LOCATION"), (60, 68, "ENVIRONMENT_ELEMENT")] }),

    ("The ancient oak tree blocked the path through the forest.", { "entities": [(4, 20, "ENVIRONMENT_ELEMENT"), (49, 55, "LOCATION")] }),
    ("Moonlight filtered through the leaves of the willow.", { "entities": [(0, 9, "ENVIRONMENT_ELEMENT"), (48, 55, "ENVIRONMENT_ELEMENT")] }),
    ("A thick fog covered the valley, obscuring the castle.", { "entities": [(2, 11, "ENVIRONMENT_ELEMENT"), (24, 30, "LOCATION"), (45, 51, "LOCATION")] }),
    ("The crystal waterfall sparkled in the morning light.", { "entities": [(4, 22, "ENVIRONMENT_ELEMENT")] }),
    ("Rocks tumbled down the cliffside during the earthquake.", { "entities": [(0, 5, "ENVIRONMENT_ELEMENT"), (23, 32, "LOCATION")] }),

    ("Alice picked up the silver key from the wooden chest.", { "entities": [(0, 5, "CHARACTER"), (21, 31, "ITEM"), (41, 54, "ITEM")] }),
    ("The wizard's staff glowed blue during the Ritual of Light.", { "entities": [(4, 10, "CHARACTER"), (13, 18, "ITEM"), (41, 57, "EVENT")] }),
    ("He drew his rusted sword before the battle began.", { "entities": [(14, 26, "ITEM")] }),
    ("Maria found a leather pouch hidden in the old oak.", { "entities": [(0, 5, "CHARACTER"), (16, 30, "ITEM"), (48, 51, "ENVIRONMENT_ELEMENT")] }),
    ("The ancient book contained secrets about the Great War.", { "entities": [(4, 16, "ITEM"), (49, 58, "EVENT")] }),

    ("The wizard cast a powerful spell during the eclipse.", { "entities": [(4, 10, "CHARACTER"), (16, 21, "ITEM"), (41, 48, "ENVIRONMENT_ELEMENT")] }),
    ("The battle began at sunrise near the river.", { "entities": [(36, 42, "LOCATION")] }),
    ("Captain Blackbeard sailed away from the cursed island.", { "entities": [(0, 18, "CHARACTER"), (43, 56, "LOCATION")] }),
    ("The princess smiled warmly during the Royal Banquet.", { "entities": [(4, 12, "CHARACTER"), (37, 51, "EVENT")] }),
    ("Detective Holmes solved the mystery in the library.", { "entities": [(0, 17, "CHARACTER"), (43, 50, "LOCATION")] }),

    ("The Great War changed the fate of the kingdom.", {"entities": [(4, 13, "EVENT"), (38, 45, "LOCATION")] }),
    ("The Rebellion of Wizards shook the foundations of the Tower.", { "entities": [(4, 26, "EVENT"), (58, 63, "LOCATION")] }),
    ("During the Fall of Athens, many artifacts were lost.", { "entities": [(12, 26, "EVENT"), (33, 42, "ITEM")] }),
    ("The Coronation of Queen Alice was held in the Grand Hall.", { "entities": [(4, 30, "EVENT"), (49, 59, "LOCATION")] }),
    ("The Treaty of Shadows ended the conflict between the clans.", { "entities": [(4, 25, "EVENT"), (58, 63, "GROUP")] }),

    ("John walked across the misty field at sunrise.", { "entities": [(0, 4, "CHARACTER"), (32, 37, "LOCATION")] }),
    ("The ranger observed the tall pine tree near the riverbank.", { "entities": [(4, 10, "CHARACTER"), (25, 39, "ENVIRONMENT_ELEMENT"), (49, 59, "LOCATION")] }),
    ("A caravan of traders crossed the desert during the Sandstorm of Ages.", { "entities": [(2, 21, "GROUP"), (34, 40, "LOCATION"), (52, 70, "EVENT")] }),
    ("The blacksmith forged a steel sword inside the workshop.", { "entities": [(4, 14, "CHARACTER"), (23, 34, "ITEM"), (46, 56, "LOCATION")] }),
    ("Elena discovered a hidden cave behind the roaring waterfall.", { "entities": [(0, 5, "CHARACTER"), (24, 35, "LOCATION"), (47, 66, "ENVIRONMENT_ELEMENT")] }),

    ("The council assembled during the Gathering of Kings.", { "entities": [(4, 11, "GROUP"), (31, 49, "EVENT")] }),
    ("A flock of birds flew over the ancient ruins at dusk.", { "entities": [(2, 16, "GROUP"), (31, 45, "LOCATION")] }),
    ("The hunter carried a wooden spear through the jungle.", { "entities": [(4, 10, "CHARACTER"), (21, 33, "ITEM"), (45, 51, "LOCATION")] }),
    ("The glowing crystal illuminated the cavern during the Ritual of Fire.", { "entities": [(4, 19, "ENVIRONMENT_ELEMENT"), (34, 40, "LOCATION"), (52, 67, "EVENT")] }),
    ("The queen hosted the Grand Feast in the marble hall.", { "entities": [(4, 9, "CHARACTER"), (21, 32, "EVENT"), (40, 51, "LOCATION")] }),

    ("A storm raged across the ocean during the Night of Thunder.", { "entities": [(2, 7, "ENVIRONMENT_ELEMENT"), (27, 32, "LOCATION"), (44, 61, "EVENT")] }),
    ("The explorer mapped the jungle using an ancient compass.", { "entities": [(4, 12, "CHARACTER"), (24, 30, "LOCATION"), (40, 55, "ITEM")] }),
    ("Villagers rebuilt their homes after the Great Flood.", { "entities": [(0, 9, "GROUP"), (41, 52, "EVENT")] }),
    ("The knight raised his shield before the Battle of Dawn.", { "entities": [(4, 10, "CHARACTER"), (22, 28, "ITEM"), (39, 54, "EVENT")] }),
    ("A circle of druids gathered near the sacred oak tree.", { "entities": [(2, 18, "GROUP"), (36, 53, "ENVIRONMENT_ELEMENT")] }),

    ("He held the iron key.", {"entities": [(13, 22, "ITEM")]}),
    ("The key opened the castle door.", {"entities": [(4, 7, "ITEM"), (20, 32, "LOCATION")]}),
    ("She touched the mossy stone.", {"entities": [(15, 26, "ENVIRONMENT_ELEMENT")]}),
    ("The stone blocked the path.", {"entities": [(4, 9, "ITEM")]}),

    ("The Winter Festival of Lanterns filled the town square with light.", { "entities": [(4, 30, "EVENT"), (40, 51, "LOCATION")] }),
    ("During the Eclipse of the Twin Suns, the ruins became visible again.", { "entities": [(12, 35, "EVENT"), (42, 48, "LOCATION")] }),
    ("The Battle of Crimson Peak ended the war between the kingdoms.", { "entities": [(4, 25, "EVENT")] }),
    ("The Ceremony of Silent Oaths was held in the Grand Cathedral.", { "entities": [(4, 30, "EVENT"), (43, 60, "LOCATION")] }),
    ("The Fall of the Iron Empire reshaped the entire continent.", { "entities": [(4, 28, "EVENT")] }),
    ("The Night of Falling Stars is remembered across the northern lands.", { "entities": [(4, 26, "EVENT"), (45, 59, "LOCATION")] }),
    ("The Expedition of the Lost World uncovered ancient artifacts.", { "entities": [(4, 29, "EVENT"), (41, 48, "ITEM")] }),
    ("The Festival of Broken Mirrors took place in the old palace courtyard.", { "entities": [(4, 30, "EVENT"), (48, 69, "LOCATION")] }),
    ("The Treaty of Endless Night ended centuries of conflict.", { "entities": [(4, 27, "EVENT")] }),
    ("The Coronation of Queen Seraphine was celebrated in the marble hall.", { "entities": [(4, 34, "EVENT"), (53, 63, "LOCATION")] }),

    ("A brass compass lay on the wooden desk beside the lantern.", { "entities": [(2, 15, "ITEM"), (23, 34, "ITEM"), (44, 51, "ITEM")] }),
    ("The silver dagger was hidden under the stone steps near the cellar entrance.", { "entities": [(4, 17, "ITEM"), (36, 47, "ENVIRONMENT_ELEMENT"), (56, 62, "LOCATION")] }),
    ("A glass vial of blue liquid rested in the iron cabinet.", { "entities": [(2, 13, "ITEM"), (42, 55, "ITEM")] }),
    ("The ancient scroll was sealed inside a carved wooden box.", { "entities": [(4, 18, "ITEM"), (41, 56, "ITEM")] }),
    ("A golden amulet hung from a rusted chain in the crypt.", { "entities": [(2, 14, "ITEM"), (28, 41, "ITEM"), (49, 54, "LOCATION")] }),
    ("The iron key was found inside a cracked stone wall.", { "entities": [(4, 12, "ITEM"), (34, 46, "ENVIRONMENT_ELEMENT")] }),
    ("A leather-bound journal lay beneath the pillow in the attic room.", { "entities": [(2, 24, "ITEM"), (36, 42, "ITEM"), (50, 60, "LOCATION")] }),
    ("The crystal orb rested on a pedestal carved from obsidian.", { "entities": [(4, 16, "ITEM"), (29, 37, "ENVIRONMENT_ELEMENT")] }),
    ("A rusted sword was embedded in the frozen ground near the battlefield.", { "entities": [(2, 14, "ITEM"), (34, 48, "ENVIRONMENT_ELEMENT"), (57, 68, "LOCATION")] }),
    ("The marble statue stood at the center of the ruined plaza.", { "entities": [(4, 17, "ITEM"), (43, 57, "LOCATION")] }),

    ("The abandoned lighthouse stood on the edge of the stormy coast.", { "entities": [(4, 26, "LOCATION"), (45, 60, "ENVIRONMENT_ELEMENT")] }),
    ("A frozen river cut through the valley beneath the snowy cliffs.", { "entities": [(2, 14, "ENVIRONMENT_ELEMENT"), (31, 37, "LOCATION"), (50, 63, "ENVIRONMENT_ELEMENT")] }),
    ("The ancient forest stretched beyond the mist-covered hills.", { "entities": [(4, 20, "LOCATION"), (33, 59, "ENVIRONMENT_ELEMENT")] }),
    ("A narrow canyon split the desert in two under the burning sun.", { "entities": [(2, 15, "LOCATION"), (25, 31, "LOCATION")] }),
    ("The crystal cave shimmered beneath the glacier.", { "entities": [(4, 16, "LOCATION"), (36, 44, "LOCATION")] }),
    ("A ruined fortress overlooked the black marsh.", { "entities": [(2, 17, "LOCATION"), (35, 46, "LOCATION")] }),
    ("The sunken temple lay beneath the waves of the deep sea.", { "entities": [(4, 17, "LOCATION"), (33, 44, "LOCATION")] }),
    ("A floating island drifted above the endless clouds.", { "entities": [(2, 16, "LOCATION"), (33, 50, "ENVIRONMENT_ELEMENT")] }),
    ("The burning plains stretched toward the horizon.", { "entities": [(4, 17, "LOCATION")] }),
    ("A hidden valley was surrounded by towering mountain peaks.", { "entities": [(2, 15, "LOCATION"), (40, 59, "ENVIRONMENT_ELEMENT")] }),

    ("The wooden chair stood beside a broken table in the dining hall.", { "entities": [(4, 17, "ITEM"), (31, 44, "ITEM"), (52, 63, "LOCATION")] }),
    ("A bronze helmet lay on the stone floor of the armory.", { "entities": [(2, 15, "ITEM"), (27, 38, "ENVIRONMENT_ELEMENT"), (47, 53, "LOCATION")] }),
    ("The iron shield hung above the fireplace in the great hall.", { "entities": [(4, 16, "ITEM"), (32, 42, "ENVIRONMENT_ELEMENT"), (50, 59, "LOCATION")] }),
    ("A carved wooden box contained maps of unknown lands.", { "entities": [(2, 22, "ITEM"), (34, 38, "ITEM")] }),
    ("The silver ring rested inside a velvet pouch on the bed.", { "entities": [(4, 15, "ITEM"), (33, 45, "ITEM"), (53, 56, "ITEM")] }),
    ("A stone tablet was embedded in the temple wall.", { "entities": [(2, 14, "ITEM"), (33, 46, "ENVIRONMENT_ELEMENT")] }),
    ("The glowing lantern was hung from the ceiling beam.", { "entities": [(4, 19, "ITEM"), (36, 50, "ENVIRONMENT_ELEMENT")] }),
    ("A wooden ladder leaned against the attic hatch.", { "entities": [(2, 16, "ITEM"), (33, 44, "ENVIRONMENT_ELEMENT")] }),
    ("The brass key opened a locked drawer in the study.", { "entities": [(4, 13, "ITEM"), (28, 34, "ITEM"), (42, 47, "LOCATION")] }),
    ("A crystal shard lay on the altar inside the sacred chamber.", { "entities": [(2, 15, "ITEM"), (26, 31, "LOCATION"), (40, 57, "LOCATION")] }),

    ("The city of Eldermere rose along the river delta.", { "entities": [(4, 21, "LOCATION"), (36, 47, "ENVIRONMENT_ELEMENT")] }),
    ("A caravan camp formed near the oasis in the shifting dunes.", { "entities": [(2, 17, "LOCATION"), (30, 35, "LOCATION")] }),
    ("The underground tunnels stretched beneath the capital city.", { "entities": [(4, 27, "LOCATION"), (42, 55, "LOCATION")] }),
    ("A monastery stood high in the misty mountains.", { "entities": [(2, 12, "LOCATION"), (27, 45, "ENVIRONMENT_ELEMENT")] }),
    ("The harbor city was protected by massive stone walls.", { "entities": [(4, 15, "LOCATION"), (35, 52, "ENVIRONMENT_ELEMENT")] }),
    ("A desert outpost marked the edge of the known world.", { "entities": [(2, 15, "LOCATION")] }),
    ("The royal palace overlooked the shining capital.", { "entities": [(4, 17, "LOCATION"), (32, 48, "LOCATION")] }),
    ("A hidden village survived deep within the enchanted forest.", { "entities": [(2, 15, "LOCATION"), (36, 59, "LOCATION")] }),
    ("The mountain pass connected two frozen kingdoms.", { "entities": [(4, 18, "LOCATION")] }),
    ("A coastal town lay beside the roaring sea.", { "entities": [(2, 15, "LOCATION"), (29, 39, "ENVIRONMENT_ELEMENT")] }),

    ("The Night of Emberfall marked the beginning of the curse.", { "entities": [(4, 22, "EVENT")] }),
    ("The Festival of the Silver Moon illuminated the entire valley.", { "entities": [(4, 28, "EVENT"), (51, 57, "LOCATION")] }),
    ("The Siege of Black Harbor lasted for seven days.", { "entities": [(4, 25, "EVENT")] }),
    ("The War of Broken Suns reshaped the ancient kingdoms.", { "entities": [(4, 23, "EVENT")] }),
    ("The Rite of Ascension was performed in the sacred temple.", { "entities": [(4, 21, "EVENT"), (44, 56, "LOCATION")] }),
    ("The March of Fallen Kings ended the age of empires.", { "entities": [(4, 24, "EVENT")] }),
    ("The Gathering of Storms brought the clans together.", { "entities": [(4, 24, "EVENT")] }),
    ("The Day of Shattered Light is remembered in every kingdom.", { "entities": [(4, 27, "EVENT")] }),
    ("The Whispering War changed the fate of the northern realms.", { "entities": [(4, 18, "EVENT"), (44, 60, "LOCATION")] }),
    ("The Age of Frozen Ash began after the great catastrophe.", { "entities": [(4, 22, "EVENT")] }),

        ("The Hollow Crown Ceremony marked the rise of a new dynasty.", { "entities": [(4, 26, "EVENT")] }),
    ("During the Blood Moon Rising, the forest became unnaturally silent.", { "entities": [(12, 29, "EVENT"), (36, 42, "LOCATION")] }),
    ("The Fall of Silverbridge destroyed the old trade routes.", { "entities": [(4, 26, "EVENT")] }),
    ("The Echoes of the Deep Festival was celebrated in the underwater city.", { "entities": [(4, 32, "EVENT"), (51, 70, "LOCATION")] }),
    ("The Shattering of the World Pillar ended the ancient age.", { "entities": [(4, 29, "EVENT")] }),
    ("The Dawn of Ember Kings is remembered in the northern chronicles.", { "entities": [(4, 23, "EVENT"), (47, 62, "LOCATION")] }),
    ("The Trial of the Nine Masks took place inside the obsidian court.", { "entities": [(4, 27, "EVENT"), (50, 65, "LOCATION")] }),
    ("The Frostfall Requiem echoed through the frozen valley.", { "entities": [(4, 22, "EVENT"), (42, 48, "LOCATION")] }),
    ("The War of Twin Thrones reshaped the eastern kingdoms.", { "entities": [(4, 23, "EVENT"), (43, 52, "LOCATION")] }),
    ("The Festival of Ashen Wings filled the skies above the capital.", { "entities": [(4, 28, "EVENT"), (50, 57, "LOCATION")] }),

    ("A wooden chest contained a broken mirror and old letters.", { "entities": [(2, 14, "ITEM"), (26, 39, "ITEM")] }),
    ("The iron lantern hung from a chain above the stone floor.", { "entities": [(4, 16, "ITEM"), (44, 55, "ENVIRONMENT_ELEMENT")] }),
    ("A silver pendant rested on a velvet cloth inside the drawer.", { "entities": [(2, 15, "ITEM"), (33, 45, "ITEM"), (53, 59, "ITEM")] }),
    ("The rusted helmet lay beside a shattered shield in the ruins.", { "entities": [(4, 17, "ITEM"), (31, 48, "ITEM")] }),
    ("A crystal vial glowed faintly on the altar stone.", { "entities": [(2, 14, "ITEM"), (33, 44, "ENVIRONMENT_ELEMENT")] }),
    ("The leather-bound book was locked in a glass case.", { "entities": [(4, 25, "ITEM"), (40, 50, "ITEM")] }),
    ("A bronze key was hidden under a pile of ashes.", { "entities": [(2, 12, "ITEM")] }),
    ("The marble chessboard was cracked down the center.", { "entities": [(4, 22, "ITEM")] }),
    ("A golden goblet stood untouched on the royal table.", { "entities": [(2, 15, "ITEM"), (41, 51, "ITEM")] }),
    ("The obsidian dagger was buried beneath the altar steps.", { "entities": [(4, 20, "ITEM"), (37, 50, "ENVIRONMENT_ELEMENT")] }),

    ("The abandoned city of Kareth fell into ruin after the war.", { "entities": [(4, 25, "LOCATION")] }),
    ("A frozen archipelago stretched across the northern sea.", { "entities": [(2, 18, "LOCATION"), (44, 56, "ENVIRONMENT_ELEMENT")] }),
    ("The obsidian cliffs rose above the black ocean.", { "entities": [(4, 20, "ENVIRONMENT_ELEMENT"), (32, 43, "ENVIRONMENT_ELEMENT")] }),
    ("A glowing desert stretched endlessly under twin suns.", { "entities": [(2, 14, "LOCATION")] }),
    ("The subterranean vaults lay beneath the royal capital.", { "entities": [(4, 25, "LOCATION"), (40, 53, "LOCATION")] }),
    ("A ruined chapel stood at the edge of the cursed marshlands.", { "entities": [(2, 16, "LOCATION"), (40, 57, "LOCATION")] }),
    ("The emerald forest hid many forgotten paths.", { "entities": [(4, 19, "LOCATION")] }),
    ("A storm-wracked coastline marked the boundary of the empire.", { "entities": [(2, 20, "LOCATION")] }),
    ("The sunlit canyon split the mountain range in two.", { "entities": [(4, 17, "LOCATION")] }),
    ("A forgotten island drifted beyond the horizon.", { "entities": [(2, 16, "LOCATION")] }),

    ("The Blade of Eternal Winter was forged in the northern forges.", { "entities": [(4, 28, "ITEM"), (45, 62, "LOCATION")] }),
    ("A map of the Hidden Realms was discovered in an ancient vault.", { "entities": [(2, 26, "ITEM"), (43, 59, "LOCATION")] }),
    ("The Crown of Broken Stars lay inside the royal treasury chamber.", { "entities": [(4, 26, "ITEM"), (38, 63, "LOCATION")] }),
    ("A book of forbidden spells was sealed with iron chains.", { "entities": [(2, 26, "ITEM")] }),
    ("The Orb of Endless Night pulsed with dark energy.", { "entities": [(4, 25, "ITEM")] }),
    ("A fragment of the World Engine was found beneath the ruins.", { "entities": [(2, 30, "ITEM"), (44, 49, "LOCATION")] }),
    ("The Shield of Dawn rested in the armory of the citadel.", { "entities": [(4, 20, "ITEM"), (33, 54, "LOCATION")] }),
    ("A relic from the First Age lay buried in volcanic ash.", { "entities": [(2, 27, "ITEM")] }),
    ("The Staff of Whispering Winds leaned against the altar stone.", { "entities": [(4, 30, "ITEM"), (44, 55, "ENVIRONMENT_ELEMENT")] }),
    ("A shard of the Sun Crystal was embedded in the mountain wall.", { "entities": [(2, 26, "ITEM"), (43, 60, "ENVIRONMENT_ELEMENT")] }),

    ("The City of Glass rose above the mirrored lake.", { "entities": [(4, 17, "LOCATION"), (32, 46, "ENVIRONMENT_ELEMENT")] }),
    ("A fortress carved into the cliff watched over the valley below.", { "entities": [(2, 10, "LOCATION"), (26, 31, "ENVIRONMENT_ELEMENT"), (44, 50, "LOCATION")] }),
    ("The underground river flowed through the crystal caves.", { "entities": [(4, 25, "ENVIRONMENT_ELEMENT"), (39, 55, "LOCATION")] }),
    ("A frozen wasteland stretched beyond the broken mountains.", { "entities": [(2, 17, "LOCATION")] }),
    ("The sunken ruins of Vhalor lay beneath the deep sea.", { "entities": [(4, 25, "LOCATION"), (39, 47, "ENVIRONMENT_ELEMENT")] }),
    ("A floating citadel drifted above the storm clouds.", { "entities": [(2, 17, "LOCATION"), (34, 48, "ENVIRONMENT_ELEMENT")] }),
    ("The cursed forest of Nyrel was avoided by all travelers.", { "entities": [(4, 26, "LOCATION")] }),
    ("A volcanic ridge divided the glowing lava fields.", { "entities": [(2, 16, "LOCATION")] }),
    ("The endless desert of Kharim swallowed entire caravans.", { "entities": [(4, 26, "LOCATION")] }),
    ("A hidden oasis survived deep within the burning dunes.", { "entities": [(2, 15, "LOCATION")] }),

    ("The Hammer of the First King lay in the ancestral forge.", { "entities": [(4, 28, "ITEM"), (39, 56, "LOCATION")] }),
    ("A sealed letter from the War of Broken Suns was found in a vault.", { "entities": [(2, 44, "ITEM"), (52, 57, "LOCATION")] }),
    ("The Mask of Silent Truth rested on a pedestal in the temple hall.", { "entities": [(4, 25, "ITEM"), (45, 65, "LOCATION")] }),
    ("A broken compass pointing nowhere lay on the shipwreck deck.", { "entities": [(2, 25, "ITEM")] }),
    ("The Chain of Eternity bound the gate to the underworld.", { "entities": [(4, 23, "ITEM")] }),
    ("A vial of moon essence was stored in the alchemist's lab.", { "entities": [(2, 22, "ITEM"), (41, 57, "LOCATION")] }),
    ("The Book of Endless Pages was kept in the forbidden library.", { "entities": [(4, 26, "ITEM"), (41, 60, "LOCATION")] }),
    ("A sword forged from star metal lay inside the royal vault.", { "entities": [(2, 30, "ITEM"), (43, 58, "LOCATION")] }),
    ("The Horn of Awakening was hidden beneath the mountain shrine.", { "entities": [(4, 22, "ITEM"), (38, 61, "LOCATION")] }),
    ("A fragment of the shattered sun rested in the desert temple.", { "entities": [(2, 31, "ITEM"), (44, 60, "LOCATION")] }),

        ("Mom): oh, yes. I agree.", {"entities": [(0, 3, "CHARACTER")]}),
    ("Why are you here? she asked.", {"entities": []}),
    ("(girl, daughter) whispered softly.", {"entities": [(1, 5, "CHARACTER"), (7, 15, "CHARACTER")]}),
    ("cutie cat purred softly under the bed.", {"entities": [(0, 9, "CHARACTER"), (29, 38, "ITEM")]}),
    ("history book lay open on the table.", {"entities": [(0, 7, "ITEM"), (8, 12, "ITEM"), (27, 32, "ITEM")]}),
    ("ancient demon appeared in the hallway!", {"entities": [(0, 13, "CHARACTER"), (27, 35, "LOCATION")]}),
    ("(Mother) said: 'Where is my notebook???'", {"entities": [(1, 7, "CHARACTER"), (27, 35, "ITEM")]}),
    ("Father: NO, I don't know!!!", {"entities": [(0, 6, "CHARACTER")]}),
    ("(little girl) - I saw it under bed!!!", {"entities": [(1, 12, "CHARACTER"), (26, 29, "ITEM")]}),
    ("cat!!! jumped!!! table!!!", {"entities": [(0, 3, "CHARACTER"), (18, 23, "ITEM")]}),

    ("[wizard??] cast spell??? tower!!!", {"entities": [(1, 7, "CHARACTER"), (26, 31, "LOCATION")]}),
    ("the OLD wizard??? shouted in forest??", {"entities": [(4, 15, "CHARACTER"), (30, 36, "LOCATION")]}),
    ("?? detective Holmes !! solved case", {"entities": [(3, 18, "CHARACTER")]}),
    ("queen??? ELIZABETH!! sat throne room", {"entities": [(0, 15, "CHARACTER"), (24, 35, "LOCATION")]}),
    ("knight... sword... battle!!!", {"entities": [(0, 6, "CHARACTER"), (8, 13, "ITEM")]}),

    ("(Captain) Blackbeard!!! sea??? crew!!!", {"entities": [(1, 9, "CHARACTER"), (20, 23, "LOCATION"), (26, 30, "GROUP")]}),
    ("stranger?? appeared?? crossroads??", {"entities": [(0, 9, "CHARACTER"), (20, 30, "LOCATION")]}),
    ("princess!!! smiled??? castle hall!!!", {"entities": [(0, 8, "CHARACTER"), (25, 36, "LOCATION")]}),
    ("wolf?? red riding hood?? forest!!", {"entities": [(0, 4, "CHARACTER"), (6, 23, "CHARACTER"), (26, 32, "LOCATION")]}),
    ("guards!!! surrounded castle??? dawn??", {"entities": [(0, 6, "GROUP"), (22, 28, "LOCATION"), (29, 33, "EVENT")]}),

    ("(girl): I saw a ghost under bed in night???", {"entities": [(1, 5, "CHARACTER"), (21, 26, "CHARACTER"), (32, 35, "ITEM")]}),
    ("mother?? notebook?? lost!!! kitchen???", {"entities": [(0, 6, "CHARACTER"), (8, 16, "ITEM"), (26, 33, "LOCATION")]}),
    ("father!!! opened door?? hallway!!!", {"entities": [(0, 6, "CHARACTER"), (18, 22, "ITEM"), (23, 30, "LOCATION")]}),
    ("cat walked under table??? window???", {"entities": [(0, 3, "CHARACTER"), (20, 25, "ITEM"), (27, 33, "LOCATION")]}),
    ("children!! laughing!! backyard party???", {"entities": [(0, 8, "GROUP"), (20, 33, "LOCATION"), (34, 39, "EVENT")]}),

    ("(ancient book) contains prophecy?? war!!!", {"entities": [(1, 13, "ITEM"), (31, 34, "EVENT")]}),
    ("!! storm!!! ocean??? night!!", {"entities": [(3, 8, "ENVIRONMENT_ELEMENT"), (10, 15, "LOCATION"), (17, 22, "EVENT")]}),
    ("teacher??? wrote board!! classroom!!!", {"entities": [(0, 7, "CHARACTER"), (17, 22, "ITEM"), (23, 32, "LOCATION")]}),
    ("boy?? found ball!! couch??", {"entities": [(0, 3, "CHARACTER"), (11, 15, "ITEM"), (17, 22, "ITEM")]}),
    ("family!!! dinner??? kitchen!! evening???", {"entities": [(0, 6, "GROUP"), (16, 23, "LOCATION"), (24, 31, "EVENT")]}),

    ("(cat???) under blanket!! bed!!!", {"entities": [(1, 5, "CHARACTER"), (13, 20, "ITEM"), (22, 25, "ITEM")]}),
    ("lamp!!! flicker??? power outage!!!!", {"entities": [(0, 4, "ITEM"), (17, 30, "EVENT")]}),
    ("book??? fell shelf!!! sudden movement??", {"entities": [(0, 4, "ITEM"), (10, 15, "ITEM"), (17, 33, "EVENT")]}),
    ("mother father talking?? room??", {"entities": [(0, 6, "CHARACTER"), (7, 13, "CHARACTER"), (24, 28, "LOCATION")]}),
    ("door!!! creak!!! midnight silence???", {"entities": [(0, 4, "ITEM"), (17, 33, "EVENT")]}),

    ("John: I left the key on the kitchen table, I swear.", {"entities": [(0, 4, "CHARACTER"), (18, 21, "ITEM"), (29, 36, "LOCATION"), (37, 42, "ITEM")]}),
    ("Anna whispered: the forest behind the house is alive tonight.", {"entities": [(0, 4, "CHARACTER"), (27, 33, "LOCATION"), (45, 50, "LOCATION"), (60, 67, "EVENT")]}),
    ("The old man, trembling, dropped the lantern into the river.", {"entities": [(4, 11, "CHARACTER"), (37, 44, "ITEM"), (54, 59, "LOCATION")]}),
    ("(guard): nobody enters the tower after the Bell of Silence.", {"entities": [(1, 6, "CHARACTER"), (29, 34, "LOCATION"), (46, 62, "EVENT")]}),
    ("She looked at the broken mirror on the wall and sighed.", {"entities": [(20, 33, "ITEM"), (41, 45, "ENVIRONMENT_ELEMENT")]}),

    ("Brother: did you hear the wolves near the northern gate?", {"entities": [(0, 7, "CHARACTER"), (27, 33, "GROUP"), (44, 57, "LOCATION")]}),
    ("A lone traveler crossed the burning desert at dusk.", {"entities": [(2, 15, "CHARACTER"), (35, 41, "LOCATION")]}),
    ("The council argued loudly during the Night of Black Winds.", {"entities": [(4, 11, "GROUP"), (39, 60, "EVENT")]}),
    ("Mira: take the sword, leave the shield, run to the harbor!", {"entities": [(0, 4, "CHARACTER"), (15, 20, "ITEM"), (31, 37, "ITEM"), (51, 57, "LOCATION")]}),
    ("A whisper echoed through the empty halls of the palace.", {"entities": [(2, 9, "EVENT"), (28, 33, "LOCATION"), (41, 47, "LOCATION")]}),

    ("(child) I saw shadows moving inside the attic room!", {"entities": [(1, 6, "CHARACTER"), (13, 20, "CHARACTER"), (39, 50, "LOCATION")]}),
    ("The captain slammed the map onto the wooden deck.", {"entities": [(4, 11, "CHARACTER"), (23, 26, "ITEM"), (37, 49, "LOCATION")]}),
    ("A group of miners found gold beneath the mountain.", {"entities": [(2, 17, "GROUP"), (44, 52, "LOCATION")]}),
    ("Elder: the ritual begins when the third bell rings.", {"entities": [(0, 5, "CHARACTER"), (11, 17, "EVENT")]}),
    ("The wind carried ashes across the ruined village.", {"entities": [(4, 8, "ENVIRONMENT_ELEMENT"), (24, 30, "LOCATION")]}),

    ("Lena dropped her bag near the riverbank and ran.", {"entities": [(0, 4, "CHARACTER"), (17, 20, "ITEM"), (30, 39, "LOCATION")]}),
    ("A sudden explosion shook the tower and the nearby market.", {"entities": [(2, 20, "EVENT"), (30, 35, "LOCATION"), (50, 56, "LOCATION")]}),
    ("The priest held a sacred book inside the temple.", {"entities": [(4, 10, "CHARACTER"), (18, 29, "ITEM"), (41, 47, "LOCATION")]}),
    ("(king): bring me the crown from the hidden vault.", {"entities": [(1, 5, "CHARACTER"), (21, 26, "ITEM"), (41, 53, "LOCATION")]}),
    ("The storm grew stronger over the black sea.", {"entities": [(4, 9, "ENVIRONMENT_ELEMENT"), (34, 43, "LOCATION")]}),

    ("A pair of guards stood silently beside the iron gate.", {"entities": [(2, 16, "GROUP"), (41, 45, "ITEM")]}),
    ("Nora: the lantern flickered during the power outage.", {"entities": [(0, 4, "CHARACTER"), (10, 17, "ITEM"), (39, 52, "EVENT")]}),
    ("The boy hid the coin under the floorboards.", {"entities": [(4, 7, "CHARACTER"), (16, 20, "ITEM"), (32, 43, "ENVIRONMENT_ELEMENT")]}),
    ("The hunters chased the beast through the forest.", {"entities": [(4, 11, "GROUP"), (23, 28, "CHARACTER"), (41, 47, "LOCATION")]}),
    ("(woman): the child disappeared during the storm.", {"entities": [(1, 6, "CHARACTER"), (12, 17, "CHARACTER"), (33, 38, "EVENT")]}),

    ("A cracked bell hung in the abandoned church tower.", {"entities": [(2, 13, "ITEM"), (25, 44, "LOCATION")]}),
    ("Mark shouted across the canyon, but no one answered.", {"entities": [(0, 4, "CHARACTER"), (26, 32, "LOCATION")]}),
    ("The soldiers marched into the valley at sunrise.", {"entities": [(4, 12, "GROUP"), (30, 36, "LOCATION")]}),
    ("Sara: I left my notebook in the classroom again!", {"entities": [(0, 4, "CHARACTER"), (17, 25, "ITEM"), (33, 42, "LOCATION")]}),
    ("The fire spread quickly across the wooden houses.", {"entities": [(4, 8, "EVENT"), (31, 44, "LOCATION")]}),

    ("A thin layer of ice covered the lake overnight.", {"entities": [(2, 20, "ENVIRONMENT_ELEMENT"), (33, 37, "LOCATION")]}),
    ("The merchant sold rare artifacts in the market square.", {"entities": [(4, 12, "CHARACTER"), (18, 32, "ITEM"), (40, 54, "LOCATION")]}),
    ("(teacher): open the book to page ten.", {"entities": [(1, 8, "CHARACTER"), (20, 24, "ITEM")]}),
    ("The cave collapsed during the heavy rainfall.", {"entities": [(4, 8, "LOCATION"), (33, 48, "ENVIRONMENT_ELEMENT")]}),
    ("A band of rebels attacked the fortress at dawn.", {"entities": [(2, 17, "GROUP"), (29, 38, "LOCATION")]}),

    ("Tom: the door in the basement won't open.", {"entities": [(0, 3, "CHARACTER"), (9, 13, "ITEM"), (21, 29, "LOCATION")]}),
    ("The queen watched the ceremony from the balcony.", {"entities": [(4, 9, "CHARACTER"), (21, 29, "EVENT"), (39, 46, "LOCATION")]}),
    ("A strange noise came from inside the wooden chest.", {"entities": [(2, 15, "EVENT"), (42, 55, "ITEM")]}),
    ("(guard) raised his spear at the approaching figure.", {"entities": [(1, 6, "CHARACTER"), (18, 23, "ITEM")]}),
    ("The ship drifted slowly across the foggy ocean.", {"entities": [(4, 8, "ITEM"), (38, 43, "LOCATION")]}),

    ("A circle of children sat around the campfire.", {"entities": [(2, 20, "GROUP"), (35, 43, "ITEM")]}),
    ("The bell rang loudly during the evening service.", {"entities": [(4, 8, "ITEM"), (30, 45, "EVENT")]}),
    ("Mysterious lights appeared above the forest at night.", {"entities": [(0, 18, "EVENT"), (35, 41, "LOCATION")]}),
    ("(old woman): don't go near the river after sunset.", {"entities": [(1, 10, "CHARACTER"), (28, 33, "LOCATION")]}),
    ("The map revealed a hidden path through the mountains.", {"entities": [(4, 7, "ITEM"), (18, 29, "LOCATION"), (42, 51, "LOCATION")]}),

    ("Jack tripped over a stone and fell into the ditch.", {"entities": [(0, 4, "CHARACTER"), (21, 26, "ITEM"), (40, 45, "LOCATION")]}),
    ("The villagers fled the city during the great fire.", {"entities": [(4, 13, "GROUP"), (23, 27, "LOCATION"), (39, 49, "EVENT")]}),
    ("(girl): I left the doll on the bed.", {"entities": [(1, 5, "CHARACTER"), (19, 23, "ITEM"), (31, 34, "ITEM")]}),
    ("A shadow moved quickly across the narrow corridor.", {"entities": [(2, 8, "CHARACTER"), (36, 52, "LOCATION")]}),
    ("The king signed the treaty in the grand hall.", {"entities": [(4, 8, "CHARACTER"), (19, 25, "ITEM"), (33, 44, "LOCATION")]}),

    ("Rain poured over the rooftops of the ancient city.", {"entities": [(0, 4, "ENVIRONMENT_ELEMENT"), (39, 43, "LOCATION")]}),
    ("The knight placed his helmet on the stone altar.", {"entities": [(4, 10, "CHARACTER"), (22, 28, "ITEM"), (36, 47, "LOCATION")]}),
    ("(boy): the cat ran under the table again!", {"entities": [(1, 4, "CHARACTER"), (10, 13, "CHARACTER"), (29, 34, "ITEM")]}),
    ("A loud crash echoed from the upper floor.", {"entities": [(2, 12, "EVENT"), (33, 44, "LOCATION")]}),
    ("The guards opened the gate to the inner courtyard.", {"entities": [(4, 10, "GROUP"), (22, 26, "ITEM"), (34, 50, "LOCATION")]}),

    ("Elena: bring the lantern to the cave entrance.", {"entities": [(0, 5, "CHARACTER"), (17, 24, "ITEM"), (33, 47, "LOCATION")]}),
    ("The wind howled through the broken windows.", {"entities": [(4, 8, "ENVIRONMENT_ELEMENT"), (29, 44, "ITEM")]}),
    ("A hidden door led to a secret chamber underground.", {"entities": [(2, 13, "ITEM"), (31, 45, "LOCATION")]}),
    ("(hunter): tracks lead toward the frozen lake.", {"entities": [(1, 7, "CHARACTER"), (29, 40, "LOCATION")]}),
    ("The soldiers lit torches along the castle walls.", {"entities": [(4, 12, "GROUP"), (17, 24, "ITEM"), (35, 48, "LOCATION")]}),

    ("A deep rumble shook the ground beneath their feet.", {"entities": [(2, 12, "EVENT"), (24, 30, "ENVIRONMENT_ELEMENT")]}),
    ("The wizard placed the crystal on the wooden table.", {"entities": [(4, 10, "CHARACTER"), (21, 28, "ITEM"), (36, 48, "ITEM")]}),
    ("(mother): dinner is ready in the kitchen.", {"entities": [(1, 7, "CHARACTER"), (33, 40, "LOCATION")]}),
    ("The caravan rested near the oasis during the night.", {"entities": [(4, 11, "GROUP"), (27, 32, "LOCATION")]}),
    ("A bird landed softly on the window ledge.", {"entities": [(2, 6, "CHARACTER"), (27, 40, "ENVIRONMENT_ELEMENT")]}),

    ("The captain ordered the crew to prepare the ship.", {"entities": [(4, 11, "CHARACTER"), (24, 28, "GROUP"), (44, 48, "ITEM")]}),
    ("A flicker of light appeared in the distant tower.", {"entities": [(2, 18, "EVENT"), (38, 43, "LOCATION")]}),
    ("(priest): the ceremony begins at sunrise.", {"entities": [(1, 7, "CHARACTER"), (13, 21, "EVENT")]}),
    ("The boy opened the box and found a strange key.", {"entities": [(4, 7, "CHARACTER"), (19, 22, "ITEM"), (43, 46, "ITEM")]}),
    ("The river flooded the valley after the heavy rain.", {"entities": [(4, 9, "ENVIRONMENT_ELEMENT"), (22, 28, "LOCATION"), (39, 50, "ENVIRONMENT_ELEMENT")]}),

    ("A mysterious figure stood at the edge of the cliff.", {"entities": [(2, 20, "CHARACTER"), (43, 48, "LOCATION")]}),
    ("The guards patrolled the walls during the night watch.", {"entities": [(4, 10, "GROUP"), (21, 26, "LOCATION"), (39, 50, "EVENT")]}),
    ("(child): the toy is under the bed again!", {"entities": [(1, 6, "CHARACTER"), (12, 15, "ITEM"), (31, 34, "ITEM")]}),
    ("The storm clouds gathered above the mountains.", {"entities": [(4, 16, "ENVIRONMENT_ELEMENT"), (36, 45, "LOCATION")]}),
    ("A knight in armor stood silently in the courtyard.", {"entities": [(2, 8, "CHARACTER"), (40, 50, "LOCATION")]}),

    ("The fire crackled in the hearth of the old house.", {"entities": [(4, 8, "ENVIRONMENT_ELEMENT"), (24, 30, "ITEM"), (41, 50, "LOCATION")]}),
    ("Mila: don't touch the mirror in the hallway.", {"entities": [(0, 4, "CHARACTER"), (21, 27, "ITEM"), (35, 42, "LOCATION")]}),
    ("A group of children ran across the snowy field.", {"entities": [(2, 19, "GROUP"), (36, 41, "LOCATION")]}),
    ("The king raised his hand to silence the crowd.", {"entities": [(4, 8, "CHARACTER"), (37, 42, "GROUP")]}),
    ("A distant howl echoed through the forest at night.", {"entities": [(2, 14, "EVENT"), (35, 41, "LOCATION")]}),

    ("The door slammed shut during the sudden storm.", {"entities": [(4, 8, "ITEM"), (31, 44, "EVENT")]}),
    ("(captain): we sail at dawn toward the eastern islands.", {"entities": [(1, 8, "CHARACTER"), (44, 59, "LOCATION")]}),
    ("The lantern dimmed as the wind grew stronger.", {"entities": [(4, 11, "ITEM"), (25, 29, "ENVIRONMENT_ELEMENT")]}),
    ("A merchant caravan crossed the desert under the stars.", {"entities": [(2, 19, "GROUP"), (32, 38, "LOCATION")]}),
    ("The child hid behind the curtain in the dark room.", {"entities": [(4, 9, "CHARACTER"), (25, 32, "ITEM"), (40, 49, "LOCATION")]}),

    ("The bell tower stood above the quiet village.", {"entities": [(4, 14, "LOCATION"), (36, 43, "LOCATION")]}),
    ("Rita: I saw lights near the lake again.", {"entities": [(0, 4, "CHARACTER"), (26, 30, "LOCATION")]}),
    ("The soldiers defended the gate during the attack.", {"entities": [(4, 12, "GROUP"), (23, 27, "ITEM"), (39, 45, "EVENT")]}),
    ("A cold breeze moved through the open window.", {"entities": [(2, 13, "ENVIRONMENT_ELEMENT"), (36, 42, "ITEM")]}),
    ("The wizard disappeared in a flash of light.", {"entities": [(4, 10, "CHARACTER"), (28, 42, "EVENT")]}),

    ("The map showed a path leading to the hidden valley.", {"entities": [(4, 7, "ITEM"), (16, 20, "LOCATION"), (35, 47, "LOCATION")]}),
    ("A shadow passed over the sun, darkening the land.", {"entities": [(2, 8, "CHARACTER"), (21, 24, "ENVIRONMENT_ELEMENT"), (40, 44, "LOCATION")]}),
    ("(guard): stop right there at the gate!", {"entities": [(1, 6, "CHARACTER"), (31, 35, "ITEM")]}),
    ("The hunter tracked the animal through the snow.", {"entities": [(4, 10, "CHARACTER"), (23, 29, "CHARACTER"), (42, 46, "ENVIRONMENT_ELEMENT")]}),
    ("The queen entered the hall during the ceremony.", {"entities": [(4, 9, "CHARACTER"), (21, 25, "LOCATION"), (37, 45, "EVENT")]}),

    ("The little girl held the red apple tightly.", {"entities": [(4, 15, "CHARACTER"), (25, 34, "ITEM")]}),
    ("A tall man entered the dark room silently.", {"entities": [(2, 10, "CHARACTER"), (24, 33, "LOCATION")]}),
    ("The old wooden door creaked during the silent night.", {"entities": [(4, 19, "ITEM"), (40, 52, "EVENT")]}),
    ("(young boy): I found the hidden key under the bed.", {"entities": [(1, 10, "CHARACTER"), (24, 34, "ITEM"), (45, 48, "ITEM")]}),
    ("A small group gathered near the ancient temple.", {"entities": [(2, 13, "GROUP"), (31, 45, "LOCATION")]}),

    ("The brave knight lifted the heavy shield.", {"entities": [(4, 16, "CHARACTER"), (29, 41, "ITEM")]}),
    ("Anna: the old castle looks different at night.", {"entities": [(0, 4, "CHARACTER"), (10, 20, "LOCATION")]}),
    ("A mysterious figure walked along the narrow path.", {"entities": [(2, 19, "CHARACTER"), (38, 49, "LOCATION")]}),
    ("The quiet village rested under the pale moonlight.", {"entities": [(4, 17, "LOCATION"), (36, 51, "ENVIRONMENT_ELEMENT")]}),
    ("The young woman carried a leather bag into the crowded market.", {"entities": [(4, 15, "CHARACTER"), (26, 37, "ITEM"), (47, 61, "LOCATION")]}),

    ("(old man): the broken bridge is dangerous after the storm.", {"entities": [(1, 8, "CHARACTER"), (14, 27, "LOCATION"), (52, 57, "EVENT")]}),
    ("A dark shadow moved across the empty street.", {"entities": [(2, 13, "CHARACTER"), (33, 45, "LOCATION")]}),
    ("The royal guard opened the massive gate.", {"entities": [(4, 15, "CHARACTER"), (30, 42, "ITEM")]}),
    ("Lena found a small wooden box beneath the dusty table.", {"entities": [(0, 4, "CHARACTER"), (11, 27, "ITEM"), (45, 56, "ITEM")]}),
    ("The ancient wizard studied the glowing crystal.", {"entities": [(4, 18, "CHARACTER"), (31, 47, "ITEM")]}),

    ("A lonely child stood near the frozen lake.", {"entities": [(2, 14, "CHARACTER"), (29, 40, "LOCATION")]}),
    ("The strong wind shook the tall trees in the forest.", {"entities": [(4, 15, "ENVIRONMENT_ELEMENT"), (44, 50, "LOCATION")]}),
    ("(young girl): the black cat ran into the dark alley.", {"entities": [(1, 11, "CHARACTER"), (17, 26, "CHARACTER"), (40, 50, "LOCATION")]}),
    ("The silent crowd watched the strange ritual.", {"entities": [(4, 17, "GROUP"), (28, 43, "EVENT")]}),
    ("A clever thief stole the golden ring from the old merchant.", {"entities": [(2, 14, "CHARACTER"), (25, 37, "ITEM"), (47, 59, "CHARACTER")]}),

    ("The heavy rain flooded the narrow valley overnight.", {"entities": [(4, 14, "ENVIRONMENT_ELEMENT"), (27, 40, "LOCATION")]}),
    ("Mark: I left the small key inside the wooden chest.", {"entities": [(0, 4, "CHARACTER"), (17, 26, "ITEM"), (38, 52, "ITEM")]}),
    ("The young prince entered the grand hall during the royal ceremony.", {"entities": [(4, 16, "CHARACTER"), (25, 35, "LOCATION"), (46, 62, "EVENT")]}),
    ("A wandering traveler crossed the endless desert alone.", {"entities": [(2, 21, "CHARACTER"), (34, 49, "LOCATION")]}),
    ("The burning torch lit the dark corridor.", {"entities": [(4, 17, "ITEM"), (26, 39, "LOCATION")]}),

    ("(old woman): take the silver coin to the distant village.", {"entities": [(1, 10, "CHARACTER"), (22, 33, "ITEM"), (41, 57, "LOCATION")]}),
    ("The frightened child hid under the large table.", {"entities": [(4, 20, "CHARACTER"), (35, 46, "ITEM")]}),
    ("A broken sword lay on the cold stone floor.", {"entities": [(2, 15, "ITEM"), (27, 43, "ENVIRONMENT_ELEMENT")]}),
    ("The royal family gathered in the bright dining hall.", {"entities": [(4, 16, "GROUP"), (30, 47, "LOCATION")]}),
    ("The small boat drifted across the quiet river.", {"entities": [(4, 14, "ITEM"), (34, 45, "LOCATION")]}),

    ("Nora: the old library is full of ancient books.", {"entities": [(0, 4, "CHARACTER"), (10, 21, "LOCATION"), (35, 48, "ITEM")]}),
    ("A hidden passage led to the secret chamber below.", {"entities": [(2, 16, "LOCATION"), (30, 44, "LOCATION")]}),
    ("The tall soldier guarded the narrow bridge.", {"entities": [(4, 16, "CHARACTER"), (29, 43, "LOCATION")]}),
    ("A gentle breeze moved through the open window.", {"entities": [(2, 15, "ENVIRONMENT_ELEMENT"), (36, 42, "ITEM")]}),
    ("The curious child opened the old wooden box.", {"entities": [(4, 17, "CHARACTER"), (28, 43, "ITEM")]}),

    ("(young man): I saw a bright light above the distant mountains.", {"entities": [(1, 10, "CHARACTER"), (20, 32, "EVENT"), (44, 61, "LOCATION")]}),
    ("The dark forest stretched beyond the rolling hills.", {"entities": [(4, 15, "LOCATION"), (28, 43, "ENVIRONMENT_ELEMENT")]}),
    ("A silent hunter followed the wounded animal.", {"entities": [(2, 15, "CHARACTER"), (30, 44, "CHARACTER")]}),
    ("The old king sat on the golden throne.", {"entities": [(4, 12, "CHARACTER"), (24, 37, "ITEM")]}),
    ("The dusty road led toward the abandoned town.", {"entities": [(4, 14, "LOCATION"), (26, 41, "LOCATION")]}),

    ("Ella: bring the small lantern to the hidden cave.", {"entities": [(0, 4, "CHARACTER"), (15, 28, "ITEM"), (37, 48, "LOCATION")]}),
    ("The broken window rattled during the strong wind.", {"entities": [(4, 17, "ITEM"), (37, 49, "ENVIRONMENT_ELEMENT")]}),
    ("A young knight trained in the large courtyard.", {"entities": [(2, 14, "CHARACTER"), (29, 44, "LOCATION")]}),
    ("The quiet lake reflected the bright stars above.", {"entities": [(4, 14, "LOCATION"), (29, 41, "ENVIRONMENT_ELEMENT")]}),
    ("The small child held the soft blanket tightly.", {"entities": [(4, 15, "CHARACTER"), (25, 37, "ITEM")]}),

    ("(old guard): nobody enters the inner castle at night.", {"entities": [(1, 10, "CHARACTER"), (33, 45, "LOCATION")]}),
    ("A thin layer of snow covered the frozen ground.", {"entities": [(2, 21, "ENVIRONMENT_ELEMENT"), (34, 47, "ENVIRONMENT_ELEMENT")]}),
    ("The brave hero saved the frightened villagers.", {"entities": [(4, 14, "CHARACTER"), (25, 45, "GROUP")]}),
    ("The narrow tunnel led to the underground chamber.", {"entities": [(4, 17, "LOCATION"), (31, 51, "LOCATION")]}),
    ("A flickering candle stood on the wooden table.", {"entities": [(2, 19, "ITEM"), (32, 44, "ITEM")]}),

    ("Liam: the old bridge collapsed during the heavy storm.", {"entities": [(0, 4, "CHARACTER"), (10, 20, "LOCATION"), (44, 56, "EVENT")]}),
    ("The silent assassin moved through the dark corridor.", {"entities": [(4, 20, "CHARACTER"), (38, 51, "LOCATION")]}),
    ("A group of travelers rested near the small campfire.", {"entities": [(2, 21, "GROUP"), (37, 51, "ITEM")]}),
    ("The golden crown lay inside the royal chamber.", {"entities": [(4, 17, "ITEM"), (33, 47, "LOCATION")]}),
    ("The distant mountains were covered in thick fog.", {"entities": [(4, 22, "LOCATION"), (38, 47, "ENVIRONMENT_ELEMENT")]}),

    ("(young girl): the small dog ran into the busy street.", {"entities": [(1, 11, "CHARACTER"), (17, 26, "CHARACTER"), (40, 51, "LOCATION")]}),
    ("The old farmer worked in the wide field all day.", {"entities": [(4, 14, "CHARACTER"), (28, 38, "LOCATION")]}),
    ("A glowing crystal rested on the ancient altar.", {"entities": [(2, 17, "ITEM"), (32, 46, "LOCATION")]}),
    ("The strong warrior lifted the heavy sword easily.", {"entities": [(4, 18, "CHARACTER"), (31, 43, "ITEM")]}),
    ("The quiet child listened to the soft music.", {"entities": [(4, 15, "CHARACTER"), (30, 40, "EVENT")]}),

    ("Mira: the hidden door is behind the large bookshelf.", {"entities": [(0, 4, "CHARACTER"), (10, 21, "ITEM"), (36, 51, "ITEM")]}),
    ("The old ship drifted across the endless ocean.", {"entities": [(4, 12, "ITEM"), (34, 48, "LOCATION")]}),
    ("A brave soldier defended the city during the attack.", {"entities": [(2, 15, "CHARACTER"), (30, 34, "LOCATION"), (45, 51, "EVENT")]}),
    ("The broken statue stood in the empty courtyard.", {"entities": [(4, 18, "ITEM"), (33, 48, "LOCATION")]}),
    ("The dark clouds gathered above the silent valley.", {"entities": [(4, 16, "ENVIRONMENT_ELEMENT"), (37, 50, "LOCATION")]}),

    ("(old priest): the sacred ritual begins at midnight.", {"entities": [(1, 11, "CHARACTER"), (17, 31, "EVENT")]}),
    ("The small village slept under the pale stars.", {"entities": [(4, 17, "LOCATION"), (35, 45, "ENVIRONMENT_ELEMENT")]}),
    ("A wandering spirit appeared near the ancient ruins.", {"entities": [(2, 19, "CHARACTER"), (35, 49, "LOCATION")]}),
    ("The young boy dropped the glass bottle on the floor.", {"entities": [(4, 13, "CHARACTER"), (24, 36, "ITEM")]}),
    ("The narrow street led to the crowded marketplace.", {"entities": [(4, 17, "LOCATION"), (29, 48, "LOCATION")]}),

    ("Ella: the soft pillow is on the large bed.", {"entities": [(0, 4, "CHARACTER"), (10, 21, "ITEM"), (33, 41, "ITEM")]}),
    ("The strong wind blew across the open plain.", {"entities": [(4, 15, "ENVIRONMENT_ELEMENT"), (33, 44, "LOCATION")]}),
    ("A curious child explored the dark basement alone.", {"entities": [(2, 15, "CHARACTER"), (28, 42, "LOCATION")]}),
    ("The golden sword rested in the ancient vault.", {"entities": [(4, 16, "ITEM"), (31, 44, "LOCATION")]}),
    ("The silent forest hid many secret paths.", {"entities": [(4, 18, "LOCATION"), (27, 39, "LOCATION")]}),

    ("(young boy): the red ball rolled under the wooden table.", {"entities": [(1, 10, "CHARACTER"), (16, 23, "ITEM"), (42, 54, "ITEM")]}),
    ("The old castle tower overlooked the quiet valley.", {"entities": [(4, 21, "LOCATION"), (36, 49, "LOCATION")]}),
    ("A small group of guards stood near the main gate.", {"entities": [(2, 23, "GROUP"), (39, 48, "LOCATION")]}),
    ("The bright flame flickered in the dark room.", {"entities": [(4, 16, "ENVIRONMENT_ELEMENT"), (34, 43, "LOCATION")]}),
    ("The young girl hugged the soft toy tightly.", {"entities": [(4, 14, "CHARACTER"), (25, 33, "ITEM")]}),


]

TRAIN_DATA_2 = [
    ("Alice walked through the dark garden.", {"entities": [(0, 5, "CHARACTER"), (31, 42, "LOCATION")]}),
("The old wizard cast a spell in the tower.", {"entities": [(4, 14, "CHARACTER"), (38, 43, "LOCATION")]}),
("Maria whispered a secret to John near the fountain.", {"entities": [(0, 5, "CHARACTER"), (30, 34, "CHARACTER"), (44, 56, "ENVIRONMENT_ELEMENT")]}),
("Captain Blackbeard sailed the seas with his crew.", {"entities": [(0, 19, "CHARACTER"), (31, 35, "LOCATION"), (46, 50, "GROUP")]}),
("The young princess smiled in the castle hall.", {"entities": [(4, 19, "CHARACTER"), (34, 46, "LOCATION")]}),
("Detective Holmes solved the case in his study.", {"entities": [(0, 17, "CHARACTER"), (43, 49, "LOCATION")]}),
("A mysterious stranger appeared at the crossroads.", {"entities": [(2, 22, "CHARACTER"), (40, 51, "LOCATION")]}),
("Queen Elizabeth ruled wisely from the throne room.", {"entities": [(0, 17, "CHARACTER"), (39, 51, "LOCATION")]}),
("The brave knight drew his sword before the battle.", {"entities": [(4, 17, "CHARACTER"), (27, 32, "ITEM")]}),
("Little Red Riding Hood met the wolf in the forest.", {"entities": [(0, 25, "CHARACTER"), (34, 38, "CHARACTER"), (46, 52, "LOCATION")]}),

("The royal guards surrounded the castle at dawn.", {"entities": [(4, 16, "GROUP"), (32, 38, "LOCATION")]}),
("A band of thieves stole the treasure from the vault.", {"entities": [(2, 18, "GROUP"), (30, 38, "ITEM"), (49, 54, "LOCATION")]}),
("Villagers gathered in the square during the Harvest Festival.", {"entities": [(0, 9, "GROUP"), (22, 32, "LOCATION"), (44, 60, "EVENT")]}),
("The army marched at dawn toward the enemy fortress.", {"entities": [(4, 8, "GROUP"), (37, 53, "LOCATION")]}),
("A crew of pirates searched the island for the ancient map.", {"entities": [(2, 18, "GROUP"), (30, 36, "LOCATION"), (55, 68, "ITEM")]}),

("Alice entered the dark forest near the crystal stream.", {"entities": [(0, 5, "CHARACTER"), (24, 36, "LOCATION"), (42, 57, "ENVIRONMENT_ELEMENT")]}),
("They sailed across the Atlantic Ocean toward the mysterious island.", {"entities": [(22, 38, "LOCATION"), (57, 74, "LOCATION")]}),
("The castle stood on the hill overlooking the valley.", {"entities": [(4, 10, "LOCATION"), (23, 31, "ENVIRONMENT_ELEMENT"), (44, 50, "LOCATION")]}),
("Maria lived in Paris, in a small apartment near the Seine.", {"entities": [(0, 5, "CHARACTER"), (16, 21, "LOCATION"), (56, 61, "LOCATION")]}),
("The journey to Mount Everest was dangerous due to the blizzard.", {"entities": [(15, 28, "LOCATION"), (60, 69, "ENVIRONMENT_ELEMENT")]}),

("The ancient oak tree blocked the path through the forest.", {"entities": [(4, 21, "ENVIRONMENT_ELEMENT"), (50, 56, "LOCATION")]}),
("Moonlight filtered through the leaves of the willow.", {"entities": [(0, 9, "ENVIRONMENT_ELEMENT"), (48, 55, "ENVIRONMENT_ELEMENT")]}),
("A thick fog covered the valley, obscuring the castle.", {"entities": [(2, 11, "ENVIRONMENT_ELEMENT"), (24, 30, "LOCATION"), (46, 52, "LOCATION")]}),
("The crystal waterfall sparkled in the morning light.", {"entities": [(4, 23, "ENVIRONMENT_ELEMENT")]}),
("Rocks tumbled down the cliffside during the earthquake.", {"entities": [(0, 5, "ENVIRONMENT_ELEMENT"), (23, 32, "LOCATION")]}),

("Alice picked up the silver key from the wooden chest.", {"entities": [(0, 5, "CHARACTER"), (20, 31, "ITEM"), (41, 55, "ITEM")]}),
("The wizard's staff glowed blue during the Ritual of Light.", {"entities": [(4, 11, "CHARACTER"), (13, 19, "ITEM"), (41, 58, "EVENT")]}),
("He drew his rusted sword before the battle began.", {"entities": [(12, 26, "ITEM")]}),
("Maria found a leather pouch hidden in the old oak.", {"entities": [(0, 5, "CHARACTER"), (16, 30, "ITEM"), (47, 50, "ENVIRONMENT_ELEMENT")]}),
("The ancient book contained secrets about the Great War.", {"entities": [(4, 17, "ITEM"), (49, 59, "EVENT")]}),

("The wizard cast a powerful spell during the eclipse.", {"entities": [(4, 10, "CHARACTER"), (18, 32, "ITEM"), (44, 52, "ENVIRONMENT_ELEMENT")]}),
("The battle began at sunrise near the river.", {"entities": [(36, 45, "LOCATION")]}),
("Captain Blackbeard sailed away from the cursed island.", {"entities": [(0, 19, "CHARACTER"), (44, 58, "LOCATION")]}),
("The princess smiled warmly during the Royal Banquet.", {"entities": [(4, 13, "CHARACTER"), (38, 52, "EVENT")]}),
("Detective Holmes solved the mystery in the library.", {"entities": [(0, 17, "CHARACTER"), (44, 51, "LOCATION")]}),

("The Great War changed the fate of the kingdom.", {"entities": [(4, 14, "EVENT"), (39, 46, "LOCATION")]}),
("The Rebellion of Wizards shook the foundations of the Tower.", {"entities": [(4, 26, "EVENT"), (58, 64, "LOCATION")]}),
("During the Fall of Athens, many artifacts were lost.", {"entities": [(11, 27, "EVENT"), (33, 42, "ITEM")]}),
("The Coronation of Queen Alice was held in the Grand Hall.", {"entities": [(4, 31, "EVENT"), (49, 60, "LOCATION")]}),
("The Treaty of Shadows ended the conflict between the clans.", {"entities": [(4, 25, "EVENT"), (58, 64, "GROUP")]}),
    ("The city of Eldermere rose along the river delta.", {"entities": [(4, 22, "LOCATION"), (34, 45, "ENVIRONMENT_ELEMENT")]}),
    ("A caravan camp formed near the oasis in the shifting dunes.", {"entities": [(2, 15, "LOCATION"), (30, 35, "LOCATION")]}),
    ("The underground tunnels stretched beneath the capital city.", {"entities": [(4, 25, "LOCATION"), (41, 54, "LOCATION")]}),
    ("A monastery stood high in the misty mountains.", {"entities": [(2, 12, "LOCATION"), (27, 44, "ENVIRONMENT_ELEMENT")]}),
    ("The harbor city was protected by massive stone walls.", {"entities": [(4, 16, "LOCATION"), (35, 52, "ENVIRONMENT_ELEMENT")]}),

    ("A desert outpost marked the edge of the known world.", {"entities": [(2, 16, "LOCATION")]}),
    ("The royal palace overlooked the shining capital.", {"entities": [(4, 17, "LOCATION"), (32, 48, "LOCATION")]}),
    ("A hidden village survived deep within the enchanted forest.", {"entities": [(2, 16, "LOCATION"), (36, 59, "LOCATION")]}),
    ("The mountain pass connected two frozen kingdoms.", {"entities": [(4, 18, "LOCATION")]}),
    ("A coastal town lay beside the roaring sea.", {"entities": [(2, 16, "LOCATION"), (29, 40, "ENVIRONMENT_ELEMENT")]}),

    ("The Night of Emberfall marked the beginning of the curse.", {"entities": [(4, 22, "EVENT")]}),
    ("The Festival of the Silver Moon illuminated the entire valley.", {"entities": [(4, 30, "EVENT"), (54, 60, "LOCATION")]}),
    ("The Siege of Black Harbor lasted for seven days.", {"entities": [(4, 25, "EVENT")]}),
    ("The War of Broken Suns reshaped the ancient kingdoms.", {"entities": [(4, 23, "EVENT")]}),
    ("The Rite of Ascension was performed in the sacred temple.", {"entities": [(4, 21, "EVENT"), (44, 56, "LOCATION")]}),

    ("The March of Fallen Kings ended the age of empires.", {"entities": [(4, 25, "EVENT")]}),
    ("The Gathering of Storms brought the clans together.", {"entities": [(4, 24, "EVENT")]}),
    ("The Day of Shattered Light is remembered in every kingdom.", {"entities": [(4, 26, "EVENT")]}),
    ("The Whispering War changed the fate of the northern realms.", {"entities": [(4, 18, "EVENT"), (44, 60, "LOCATION")]}),
    ("The Age of Frozen Ash began after the great catastrophe.", {"entities": [(4, 22, "EVENT")]}),

    ("The Hollow Crown Ceremony marked the rise of a new dynasty.", {"entities": [(4, 27, "EVENT")]}),
    ("During the Blood Moon Rising, the forest became unnaturally silent.", {"entities": [(12, 30, "EVENT"), (36, 42, "LOCATION")]}),
    ("The Fall of Silverbridge destroyed the old trade routes.", {"entities": [(4, 26, "EVENT")]}),
    ("The Echoes of the Deep Festival was celebrated in the underwater city.", {"entities": [(4, 32, "EVENT"), (51, 70, "LOCATION")]}),
    ("The Shattering of the World Pillar ended the ancient age.", {"entities": [(4, 33, "EVENT")]}),

    ("The Dawn of Ember Kings is remembered in the northern chronicles.", {"entities": [(4, 23, "EVENT"), (47, 62, "LOCATION")]}),
    ("The Trial of the Nine Masks took place inside the obsidian court.", {"entities": [(4, 27, "EVENT"), (50, 65, "LOCATION")]}),
    ("The Frostfall Requiem echoed through the frozen valley.", {"entities": [(4, 23, "EVENT"), (42, 48, "LOCATION")]}),
    ("The War of Twin Thrones reshaped the eastern kingdoms.", {"entities": [(4, 24, "EVENT"), (43, 52, "LOCATION")]}),
    ("The Festival of Ashen Wings filled the skies above the capital.", {"entities": [(4, 29, "EVENT"), (50, 57, "LOCATION")]}),

        ("A brass compass lay on the wooden desk beside the lantern.", {"entities": [(2, 15, "ITEM"), (23, 34, "ITEM"), (44, 51, "ITEM")]}),
    ("The silver dagger was hidden under the stone steps near the cellar entrance.", {"entities": [(4, 17, "ITEM"), (36, 47, "ENVIRONMENT_ELEMENT"), (56, 62, "LOCATION")]}),
    ("A glass vial of blue liquid rested in the iron cabinet.", {"entities": [(2, 13, "ITEM"), (42, 55, "ITEM")]}),
    ("The ancient scroll was sealed inside a carved wooden box.", {"entities": [(4, 18, "ITEM"), (41, 58, "ITEM")]}),
    ("A golden amulet hung from a rusted chain in the crypt.", {"entities": [(2, 14, "ITEM"), (28, 41, "ITEM"), (49, 54, "LOCATION")]}),

    ("The iron key was found inside a cracked stone wall.", {"entities": [(4, 12, "ITEM"), (34, 52, "ENVIRONMENT_ELEMENT")]}),
    ("A leather-bound journal lay beneath the pillow in the attic room.", {"entities": [(2, 24, "ITEM"), (36, 42, "ITEM"), (50, 60, "LOCATION")]}),
    ("The crystal orb rested on a pedestal carved from obsidian.", {"entities": [(4, 16, "ITEM"), (29, 37, "ENVIRONMENT_ELEMENT")]}),
    ("A rusted sword was embedded in the frozen ground near the battlefield.", {"entities": [(2, 14, "ITEM"), (34, 48, "ENVIRONMENT_ELEMENT"), (57, 68, "LOCATION")]}),
    ("The marble statue stood at the center of the ruined plaza.", {"entities": [(4, 17, "ITEM"), (43, 59, "LOCATION")]}),

    ("The abandoned lighthouse stood on the edge of the stormy coast.", {"entities": [(4, 26, "LOCATION"), (45, 60, "ENVIRONMENT_ELEMENT")]}),
    ("A frozen river cut through the valley beneath the snowy cliffs.", {"entities": [(2, 14, "ENVIRONMENT_ELEMENT"), (31, 37, "LOCATION"), (50, 63, "ENVIRONMENT_ELEMENT")]}),
    ("The ancient forest stretched beyond the mist-covered hills.", {"entities": [(4, 20, "LOCATION"), (33, 59, "ENVIRONMENT_ELEMENT")]}),
    ("A narrow canyon split the desert in two under the burning sun.", {"entities": [(2, 15, "LOCATION"), (25, 31, "LOCATION")]}),
    ("The crystal cave shimmered beneath the glacier.", {"entities": [(4, 16, "LOCATION"), (36, 44, "LOCATION")]}),

    ("A ruined fortress overlooked the black marsh.", {"entities": [(2, 17, "LOCATION"), (35, 46, "LOCATION")]}),
    ("The sunken temple lay beneath the waves of the deep sea.", {"entities": [(4, 17, "LOCATION"), (33, 44, "LOCATION")]}),
    ("A floating island drifted above the endless clouds.", {"entities": [(2, 16, "LOCATION"), (33, 50, "ENVIRONMENT_ELEMENT")]}),
    ("The burning plains stretched toward the horizon.", {"entities": [(4, 17, "LOCATION")]}),
    ("A hidden valley was surrounded by towering mountain peaks.", {"entities": [(2, 15, "LOCATION"), (40, 59, "ENVIRONMENT_ELEMENT")]}),

        ("The wooden chair stood beside a broken table in the dining hall.", {"entities": [(4, 17, "ITEM"), (31, 44, "ITEM"), (52, 63, "LOCATION")]}),
    ("A bronze helmet lay on the stone floor of the armory.", {"entities": [(2, 15, "ITEM"), (27, 38, "ENVIRONMENT_ELEMENT"), (47, 53, "LOCATION")]}),
    ("The iron shield hung above the fireplace in the great hall.", {"entities": [(4, 16, "ITEM"), (32, 42, "ENVIRONMENT_ELEMENT"), (50, 60, "LOCATION")]}),
    ("A carved wooden box contained maps of unknown lands.", {"entities": [(2, 22, "ITEM"), (34, 38, "ITEM")]}),
    ("The silver ring rested inside a velvet pouch on the bed.", {"entities": [(4, 15, "ITEM"), (33, 45, "ITEM"), (53, 56, "ITEM")]}),

    ("A stone tablet was embedded in the temple wall.", {"entities": [(2, 14, "ITEM"), (33, 46, "ENVIRONMENT_ELEMENT")]}),
    ("The glowing lantern was hung from the ceiling beam.", {"entities": [(4, 19, "ITEM"), (36, 50, "ENVIRONMENT_ELEMENT")]}),
    ("A wooden ladder leaned against the attic hatch.", {"entities": [(2, 16, "ITEM"), (33, 44, "ENVIRONMENT_ELEMENT")]}),
    ("The brass key opened a locked drawer in the study.", {"entities": [(4, 13, "ITEM"), (28, 34, "ITEM"), (42, 47, "LOCATION")]}),
    ("A crystal shard lay on the altar inside the sacred chamber.", {"entities": [(2, 15, "ITEM"), (26, 31, "LOCATION"), (40, 57, "LOCATION")]}),

    ("The city of Eldermere rose along the river delta.", {"entities": [(4, 22, "LOCATION"), (34, 45, "ENVIRONMENT_ELEMENT")]}),
    ("A caravan camp formed near the oasis in the shifting dunes.", {"entities": [(2, 15, "LOCATION"), (30, 35, "LOCATION")]}),
    ("The underground tunnels stretched beneath the capital city.", {"entities": [(4, 25, "LOCATION"), (41, 54, "LOCATION")]}),
    ("A monastery stood high in the misty mountains.", {"entities": [(2, 12, "LOCATION"), (27, 44, "ENVIRONMENT_ELEMENT")]}),
    ("The harbor city was protected by massive stone walls.", {"entities": [(4, 16, "LOCATION"), (35, 52, "ENVIRONMENT_ELEMENT")]}),

    ("A desert outpost marked the edge of the known world.", {"entities": [(2, 16, "LOCATION")]}),
    ("The royal palace overlooked the shining capital.", {"entities": [(4, 17, "LOCATION"), (32, 48, "LOCATION")]}),
    ("A hidden village survived deep within the enchanted forest.", {"entities": [(2, 16, "LOCATION"), (36, 59, "LOCATION")]}),
    ("The mountain pass connected two frozen kingdoms.", {"entities": [(4, 18, "LOCATION")]}),
    ("A coastal town lay beside the roaring sea.", {"entities": [(2, 16, "LOCATION"), (29, 40, "ENVIRONMENT_ELEMENT")]}),

        ("Mom: oh, yes. I agree.", {"entities": [(0, 3, "CHARACTER")]}),
    ("Why are you here? she asked.", {"entities": []}),
    ("(girl, daughter) whispered softly.", {"entities": [(1, 5, "CHARACTER"), (7, 15, "CHARACTER")]}),
    ("cutie cat purred softly under the bed.", {"entities": [(0, 9, "CHARACTER"), (29, 37, "ITEM")]}),
    ("history book lay open on the table.", {"entities": [(0, 13, "ITEM"), (27, 32, "ITEM")]}),

    ("ancient demon appeared in the hallway!", {"entities": [(0, 13, "CHARACTER"), (27, 35, "LOCATION")]}),
    ("(Mother) said: 'Where is my notebook???'", {"entities": [(1, 7, "CHARACTER"), (28, 36, "ITEM")]}),
    ("Father: NO, I don't know!!!", {"entities": [(0, 6, "CHARACTER")]}),
    ("(little girl) - I saw it under bed!!!", {"entities": [(1, 12, "CHARACTER"), (26, 29, "ITEM")]}),
    ("cat!!! jumped!!! table!!!", {"entities": [(0, 3, "CHARACTER"), (18, 23, "ITEM")]}),

    ("[wizard??] cast spell??? tower!!!", {"entities": [(1, 7, "CHARACTER"), (26, 31, "LOCATION")]}),
    ("the OLD wizard??? shouted in forest??", {"entities": [(4, 15, "CHARACTER"), (30, 36, "LOCATION")]}),
    ("?? detective Holmes !! solved case", {"entities": [(3, 18, "CHARACTER")]}),
    ("queen??? ELIZABETH!! sat throne room", {"entities": [(0, 15, "CHARACTER"), (24, 35, "LOCATION")]}),
    ("knight... sword... battle!!!", {"entities": [(0, 6, "CHARACTER"), (8, 13, "ITEM")]}),

    ("(Captain) Blackbeard!!! sea??? crew!!!", {"entities": [(1, 9, "CHARACTER"), (21, 24, "LOCATION"), (26, 30, "GROUP")]}),
    ("stranger?? appeared?? crossroads??", {"entities": [(0, 9, "CHARACTER"), (20, 30, "LOCATION")]}),
    ("princess!!! smiled??? castle hall!!!", {"entities": [(0, 8, "CHARACTER"), (25, 36, "LOCATION")]}),
    ("wolf?? red riding hood?? forest!!", {"entities": [(0, 4, "CHARACTER"), (6, 23, "CHARACTER"), (26, 32, "LOCATION")]}),
    ("guards!!! surrounded castle??? dawn??", {"entities": [(0, 6, "GROUP"), (22, 29, "LOCATION"), (30, 34, "EVENT")]}),

    ("(girl): I saw a ghost under bed in night???", {"entities": [(1, 5, "CHARACTER"), (21, 26, "CHARACTER"), (32, 36, "ITEM")]}),
    ("mother?? notebook?? lost!!! kitchen???", {"entities": [(0, 6, "CHARACTER"), (8, 16, "ITEM"), (26, 33, "LOCATION")]}),
    ("father!!! opened door?? hallway!!!", {"entities": [(0, 6, "CHARACTER"), (18, 22, "ITEM"), (23, 30, "LOCATION")]}),
    ("cat walked under table??? window???", {"entities": [(0, 3, "CHARACTER"), (20, 25, "ITEM"), (27, 33, "LOCATION")]}),
    ("children!! laughing!! backyard party???", {"entities": [(0, 8, "GROUP"), (20, 33, "LOCATION"), (34, 39, "EVENT")]}),

    ("(ancient book) contains prophecy?? war!!!", {"entities": [(1, 13, "ITEM"), (31, 34, "EVENT")]}),
    ("!! storm!!! ocean??? night!!", {"entities": [(3, 8, "ENVIRONMENT_ELEMENT"), (10, 15, "LOCATION"), (17, 22, "EVENT")]}),
    ("teacher??? wrote board!! classroom!!!", {"entities": [(0, 7, "CHARACTER"), (17, 22, "ITEM"), (23, 32, "LOCATION")]}),
    ("boy?? found ball!! couch??", {"entities": [(0, 3, "CHARACTER"), (11, 15, "ITEM"), (17, 22, "LOCATION")]}),
    ("family!!! dinner??? kitchen!! evening???", {"entities": [(0, 6, "GROUP"), (16, 23, "LOCATION"), (24, 31, "EVENT")]}),

        ("(cat???) under blanket!! bed!!!", {"entities": [(1, 4, "CHARACTER"), (13, 20, "ITEM"), (22, 25, "ITEM")]}),
    ("lamp!!! flicker??? power outage!!!!", {"entities": [(0, 4, "ITEM"), (17, 30, "EVENT")]}),
    ("book??? fell shelf!!! sudden movement??", {"entities": [(0, 4, "ITEM"), (10, 15, "ITEM"), (17, 33, "EVENT")]}),
    ("mother father talking?? room??", {"entities": [(0, 6, "CHARACTER"), (7, 13, "CHARACTER"), (24, 28, "LOCATION")]}),
    ("door!!! creak!!! midnight silence???", {"entities": [(0, 4, "ITEM"), (17, 33, "EVENT")]}),

    ("John: I left the key on the kitchen table, I swear.", {"entities": [(0, 4, "CHARACTER"), (18, 21, "ITEM"), (29, 36, "LOCATION"), (37, 42, "ITEM")]}),
    ("Anna whispered: the forest behind the house is alive tonight.", {"entities": [(0, 4, "CHARACTER"), (19, 25, "LOCATION"), (31, 36, "LOCATION"), (45, 51, "EVENT")]}),
    ("The old man, trembling, dropped the lantern into the river.", {"entities": [(4, 11, "CHARACTER"), (37, 44, "ITEM"), (49, 54, "LOCATION")]}),
    ("(guard): nobody enters the tower after the Bell of Silence.", {"entities": [(1, 6, "CHARACTER"), (25, 30, "LOCATION"), (43, 59, "EVENT")]}),
    ("She looked at the broken mirror on the wall and sighed.", {"entities": [(20, 33, "ITEM"), (37, 41, "ENVIRONMENT_ELEMENT")]}),

    ("Brother: did you hear the wolves near the northern gate?", {"entities": [(0, 7, "CHARACTER"), (28, 34, "GROUP"), (43, 57, "LOCATION")]}),
    ("A lone traveler crossed the burning desert at dusk.", {"entities": [(2, 15, "CHARACTER"), (35, 41, "LOCATION")]}),
    ("The council argued loudly during the Night of Black Winds.", {"entities": [(4, 11, "GROUP"), (39, 60, "EVENT")]}),
    ("Mira: take the sword, leave the shield, run to the harbor!", {"entities": [(0, 4, "CHARACTER"), (12, 17, "ITEM"), (27, 33, "ITEM"), (47, 53, "LOCATION")]}),
    ("A whisper echoed through the empty halls of the palace.", {"entities": [(2, 9, "EVENT"), (26, 31, "LOCATION"), (40, 46, "LOCATION")]}),

    ("(child) I saw shadows moving inside the attic room!", {"entities": [(1, 6, "CHARACTER"), (37, 49, "LOCATION")]}),
    ("The captain slammed the map onto the wooden deck.", {"entities": [(4, 11, "CHARACTER"), (23, 26, "ITEM"), (37, 48, "LOCATION")]}),
    ("A group of miners found gold beneath the mountain.", {"entities": [(2, 17, "GROUP"), (44, 52, "LOCATION")]}),
    ("Elder: the ritual begins when the third bell rings.", {"entities": [(0, 5, "CHARACTER"), (11, 17, "EVENT")]}),
    ("The wind carried ashes across the ruined village.", {"entities": [(4, 8, "ENVIRONMENT_ELEMENT"), (24, 30, "LOCATION")]}),

    ("Lena dropped her bag near the riverbank and ran.", {"entities": [(0, 4, "CHARACTER"), (17, 20, "ITEM"), (30, 39, "LOCATION")]}),
    ("A sudden explosion shook the tower and the nearby market.", {"entities": [(2, 20, "EVENT"), (30, 35, "LOCATION"), (44, 50, "LOCATION")]}),
    ("The priest held a sacred book inside the temple.", {"entities": [(4, 10, "CHARACTER"), (18, 29, "ITEM"), (41, 47, "LOCATION")]}),
    ("(king): bring me the crown from the hidden vault.", {"entities": [(1, 5, "CHARACTER"), (21, 26, "ITEM"), (38, 51, "LOCATION")]}),
    ("The storm grew stronger over the black sea.", {"entities": [(4, 9, "ENVIRONMENT_ELEMENT"), (34, 43, "LOCATION")]}),

    ("A pair of guards stood silently beside the iron gate.", {"entities": [(2, 16, "GROUP"), (41, 45, "ITEM")]}),
    ("Nora: the lantern flickered during the power outage.", {"entities": [(0, 4, "CHARACTER"), (10, 17, "ITEM"), (39, 52, "EVENT")]}),
    ("The boy hid the coin under the floorboards.", {"entities": [(4, 7, "CHARACTER"), (16, 20, "ITEM"), (32, 43, "ENVIRONMENT_ELEMENT")]}),
    ("The hunters chased the beast through the forest.", {"entities": [(4, 11, "GROUP"), (23, 28, "CHARACTER"), (41, 47, "LOCATION")]}),
    ("(woman): the child disappeared during the storm.", {"entities": [(1, 6, "CHARACTER"), (12, 17, "CHARACTER"), (33, 38, "EVENT")]}),

    ("A cracked bell hung in the abandoned church tower.", {"entities": [(2, 13, "ITEM"), (25, 44, "LOCATION")]}),
    ("Mark shouted across the canyon, but no one answered.", {"entities": [(0, 4, "CHARACTER"), (26, 32, "LOCATION")]}),
    ("The soldiers marched into the valley at sunrise.", {"entities": [(4, 12, "GROUP"), (30, 36, "LOCATION")]}),
    ("Sara: I left my notebook in the classroom again!", {"entities": [(0, 4, "CHARACTER"), (17, 25, "ITEM"), (33, 42, "LOCATION")]}),
    ("The fire spread quickly across the wooden houses.", {"entities": [(4, 8, "EVENT"), (31, 44, "LOCATION")]}),

    ("The little girl read a dusty book in the quiet library.", {"entities": [(4, 15, "CHARACTER"), (24, 34, "ITEM"), (38, 51, "LOCATION")]}),
("A tall knight guarded the ancient bridge at dawn.", {"entities": [(2, 12, "CHARACTER"), (26, 40, "LOCATION"), (44, 48, "EVENT")]}),
("The old wizard brewed a glowing potion in his hidden hut.", {"entities": [(4, 14, "CHARACTER"), (26, 40, "ITEM"), (45, 55, "LOCATION")]}),
("A young hunter tracked the deer through the snowy forest.", {"entities": [(2, 14, "CHARACTER"), (29, 33, "CHARACTER"), (42, 55, "LOCATION")]}),
("The royal queen addressed the silent crowd in the grand hall.", {"entities": [(4, 15, "CHARACTER"), (31, 44, "GROUP"), (48, 58, "LOCATION")]}),
("A broken sword lay beside the burned village after the raid.", {"entities": [(2, 14, "ITEM"), (29, 43, "LOCATION"), (49, 53, "EVENT")]}),
("The black cat jumped onto the wooden table in the kitchen.", {"entities": [(4, 14, "CHARACTER"), (31, 43, "ITEM"), (47, 55, "LOCATION")]}),
("A wandering monk crossed the misty mountains at sunrise.", {"entities": [(2, 16, "CHARACTER"), (30, 44, "LOCATION"), (48, 55, "EVENT")]}),
("The ancient book revealed secrets of the lost kingdom.", {"entities": [(4, 16, "ITEM"), (30, 43, "LOCATION")]}),
("A brave soldier carried a heavy shield across the battlefield.", {"entities": [(2, 15, "CHARACTER"), (27, 40, "ITEM"), (47, 58, "LOCATION")]}),
("The glowing lantern illuminated the dark corridor silently.", {"entities": [(4, 19, "ITEM"), (35, 48, "LOCATION")]}),
("A small village rested near the frozen river valley.", {"entities": [(2, 15, "LOCATION"), (30, 50, "LOCATION")]}),
("The silver crown rested on a velvet pillow in the treasury.", {"entities": [(4, 16, "ITEM"), (29, 42, "ITEM"), (47, 55, "LOCATION")]}),
("A fierce dragon circled above the burning cliffs.", {"entities": [(2, 15, "CHARACTER"), (34, 48, "LOCATION")]}),
("The silent monk prayed inside the stone temple.", {"entities": [(4, 16, "CHARACTER"), (30, 45, "LOCATION")]}),
("A golden key opened the secret chamber under the castle.", {"entities": [(2, 12, "ITEM"), (26, 41, "LOCATION"), (46, 52, "LOCATION")]}),
("The old fisherman sailed across the calm sea.", {"entities": [(4, 16, "CHARACTER"), (32, 41, "LOCATION")]}),
("A group of rebels gathered in the hidden cave.", {"entities": [(2, 18, "GROUP"), (32, 45, "LOCATION")]}),
("The dusty road led toward the ruined fortress.", {"entities": [(4, 14, "LOCATION"), (30, 45, "LOCATION")]}),
("A mysterious stranger appeared at the city gate.", {"entities": [(2, 21, "CHARACTER"), (36, 45, "LOCATION")]}),
("The iron shield blocked the attack in the narrow pass.", {"entities": [(4, 15, "ITEM"), (29, 35, "EVENT"), (39, 52, "LOCATION")]}),
("A soft wind moved through the green valley.", {"entities": [(2, 10, "ENVIRONMENT_ELEMENT"), (30, 42, "LOCATION")]}),
("The old king sat on the golden throne in silence.", {"entities": [(4, 12, "CHARACTER"), (24, 37, "ITEM")]}),
("A child found a glass marble under the bed.", {"entities": [(2, 7, "CHARACTER"), (15, 27, "ITEM"), (31, 34, "ITEM")]}),
("The burning torch lit the stone stairs in the dungeon.", {"entities": [(4, 17, "ITEM"), (25, 37, "ITEM"), (41, 48, "LOCATION")]}),
("A lone traveler crossed the endless desert at night.", {"entities": [(2, 16, "CHARACTER"), (30, 44, "LOCATION")]}),
("The icy wind swept across the frozen lake.", {"entities": [(4, 12, "ENVIRONMENT_ELEMENT"), (30, 41, "LOCATION")]}),
("A wandering bard sang inside the crowded tavern.", {"entities": [(2, 16, "CHARACTER"), (30, 46, "LOCATION")]}),
("The broken mirror reflected the empty room.", {"entities": [(4, 17, "ITEM"), (31, 41, "LOCATION")]}),
("A silver dagger was hidden beneath the old floorboards.", {"entities": [(2, 14, "ITEM"), (33, 48, "ENVIRONMENT_ELEMENT")]}),
("The blacksmith forged a sharp axe in the noisy workshop.", {"entities": [(4, 15, "CHARACTER"), (27, 36, "ITEM"), (40, 56, "LOCATION")]}),
("A peaceful meadow stretched beyond the river bend.", {"entities": [(2, 17, "LOCATION"), (31, 43, "LOCATION")]}),
("The cursed castle stood on the stormy hill.", {"entities": [(4, 18, "LOCATION"), (32, 43, "LOCATION")]}),
("A young princess danced in the glowing palace hall.", {"entities": [(2, 15, "CHARACTER"), (29, 50, "LOCATION")]}),
("The iron gate creaked during the midnight storm.", {"entities": [(4, 13, "ITEM"), (29, 42, "EVENT")]}),
("A wandering thief stole a golden ring from the merchant.", {"entities": [(2, 16, "CHARACTER"), (26, 37, "ITEM"), (45, 53, "CHARACTER")]}),
("The crystal cave shimmered under the pale light.", {"entities": [(4, 16, "LOCATION"), (30, 40, "ENVIRONMENT_ELEMENT")]}),
("A brave hero entered the forbidden forest.", {"entities": [(2, 12, "CHARACTER"), (26, 42, "LOCATION")]}),
("The wooden bridge collapsed into the rushing river.", {"entities": [(4, 17, "ITEM"), (31, 44, "LOCATION")]}),
("A royal messenger delivered a sealed letter to the palace.", {"entities": [(2, 17, "CHARACTER"), (31, 44, "ITEM"), (49, 55, "LOCATION")]}),
("The silent forest hid many ancient secrets.", {"entities": [(4, 17, "LOCATION"), (28, 43, "ITEM")]}),
("A glowing orb floated above the marble altar.", {"entities": [(2, 13, "ITEM"), (31, 45, "LOCATION")]}),
("The stormy sea swallowed the broken ship.", {"entities": [(4, 15, "LOCATION"), (29, 40, "ITEM")]}),
("A dark tunnel led to the underground city.", {"entities": [(2, 13, "LOCATION"), (27, 42, "LOCATION")]}),
("The wandering scholar studied in the quiet library.", {"entities": [(4, 22, "CHARACTER"), (36, 49, "LOCATION")]}),
("A fierce warrior defended the burning village.", {"entities": [(2, 17, "CHARACTER"), (31, 45, "LOCATION")]}),
("The golden statue stood in the sunlit square.", {"entities": [(4, 17, "ITEM"), (31, 44, "LOCATION")]}),
("A hidden passage opened behind the stone wall.", {"entities": [(2, 16, "LOCATION"), (30, 40, "ENVIRONMENT_ELEMENT")]}),
("The lonely child waited near the abandoned station.", {"entities": [(4, 16, "CHARACTER"), (30, 50, "LOCATION")]}),
("A silver bell rang in the silent chapel.", {"entities": [(2, 13, "ITEM"), (27, 40, "LOCATION")]}),
("The ancient forest whispered through the night wind.", {"entities": [(4, 19, "LOCATION"), (35, 46, "ENVIRONMENT_ELEMENT")]}),
("A small boat drifted across the misty river.", {"entities": [(2, 12, "ITEM"), (30, 43, "LOCATION")]}),
]